### ISSUE TITLE
Problems with lein-droid

### ISSUE THREAD

**Issue by roti** [laurentpetit/ccw#840] opened 2015-08-08 13:27 UTC
Hi,

After creating a new project using the "droid" template (for android apps with lein-droid), the project has several errors, among which the most important one is:
> Leiningen Managed Dependencies issue: problem resolving following dependencies: [com.android.support/multidex "1.0.0"]

To create a project using the droid template, in the "New clojure project" wizard, I entered following in the "Leiningen template" field: `droid com.myapp :target-sdk 19 :min-sdk 15`. After creating the project, one must also enter the path where android-sdk is installed in project.clj (in option :android :sdk-path). The errors persist event after setting the correct path.

A second problem is that I can't run `lein droid doall`, from within ccw (using the shortcut Alt-L L). The execution hangs at some point, and never finishes. Running it from command line works fine.

**Comment by laurentpetit** [comment] 2015-08-13 09:37
OK I'll try to reproduce it to understand what's happening.
Can you help me get up to speed by providing simplified install step of the android-sdk and potential other downloads that I should do?

**Comment by roti** [comment] 2015-08-13 12:38
So, you basically only need the android sdk.
http://developer.android.com/sdk/installing/index.html?pkg=tools

After installing you need to start the SDK Manager, and download some libraries and VM images. When starting it for the first time, the Manager suggest some packages to download. I recommend following that suggestion, with the exception of packages from Android M and Android 5.x, and download Android 4.4.2 (API19) instead . That is because by default lein-droid targets API19, so it is safer to use that Android version. Also make sure you download the "Android Support Library" and "Intel x86 Emulator Accelerator (HAXM Installer)". The latter you need to speed up your emulator (it will be used when you set the CPU of a virtual device to Intel Atom).

You could also install the eclipse plugin (http://developer.android.com/sdk/installing/installing-adt.html), but it would help you only to start the package manager and emulator from eclipse menus. You can always use the command line tools for that.
The SDK Manager is started with "tools\android".
The Virtual Device Emulator is started with "tools\android avd".

It's only a guess, but the problems could be caused by the fact that android libraries are packaged differently: aar instead of jar.

**Comment by arichiardi** [comment] 2015-08-13 13:40
It can be the packaging, but shouldn't lein-droid handle that? I don't think will ```lein``` ever fix the library (if that is the issue) problem.

**Comment by laurentpetit** [comment] 2015-08-13 13:44
Hi Andrea,

I do not says I understand everything about it right now :-)
But if something works with leiningen command line and not ccw, then I need
to check that.

Le jeudi 13 août 2015, Andrea Richiardi <notifications@github.com> a écrit :

> It can be the packaging, but shouldn't lein-droid handle that? I don't
> think will lein ever fix the library (if that is the issue) problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/840#issuecomment-130675809>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment] 2015-08-13 13:57
Yes, I agree :eyeglasses: 

I have worked with Android quite extensively with Android Studio and I was pondering about this issue. I don't know the inners of ```lein-droid``` but I think that it should handle three peculiar things of Android...and I just wanted to point them out to help debugging :smile: :
1) It should allow importing .aar files (same as .jar but with Android-specific resources)
2) It should handle the maven dependency (necessary) not located in your ```.m2``` but in the ```$ANDROID-SDK/extras/android/m2repository/``` folder.
3) It should include ```$ANDROID-SDK/tools``` in the $PATH

Maybe one or the other can be the issue. In particular, after a quick ```find```, I have noticed that ```multidex.jar``` is exactly in ```$ANDROID-SDK/extras/android/m2repository/com/android/support/multidex/```. It might be that ```lein-droid``` mishandles this folder.

**Comment by laurentpetit** [comment] 2015-08-13 14:08
ok, using the android sdk to download missing stuff right now.
I would like to have a success from the command line and a minimalistic project started from lein-droid, before trying to reproduce the issue from within CCW.
I don't know if the instructions given in the initial comment will help get there quickly.
I'll try lein droid doall.
Could be fun if I was able to launch the emulator after that, thus seing the "hello world" (?) app run. What should the command line lein or android-sdk command be for that?

**Comment by arichiardi** [comment] 2015-08-13 14:11
Maybe [this](https://github.com/clojure-android/lein-droid/wiki/Tutorial) is a better starting point

**Comment by laurentpetit** [comment] 2015-08-13 14:18
Ah, it says JDK 1.7 exactly, but I have jdk 1.8 on my mac os x :-(

2015-08-13 16:11 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Maybe this <https://github.com/clojure-android/lein-droid/wiki/Tutorial>
> is a better starting point
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/840#issuecomment-130689595>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment] 2015-08-13 14:21
I can try here, now  I am trying to debug  the ```swtbot-generator``` branch...

**Comment by laurentpetit** [comment] 2015-08-13 14:29
When executing `lein droid doall` from the command line, I get this problem:
```
myapp % lein-stable droid doall
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.pom from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0-beta3-r2/clojure-1.7.0-beta3-r2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.jar from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.jar from clojars
Could not find artifact com.android.support:multidex:aar:1.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in clojars (https://clojars.org/repo/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-support (file:///Users/laurentpetit/android-sdk-macosx/extras/android/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-play-services (file:///Users/laurentpetit/android-sdk-macosx/extras/google/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in maven-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I am not behind a proxy, and I have only modified `project.clj` to set the proper path to my `android-sdk-macosx`. I have tried the command twice in case the network had an intermittent problem

**Comment by arichiardi** [comment] 2015-08-13 14:30
That is exactly what my fear was, it looks it is not looking into ```$ANDROID-SDK/extras/android/m2repository/```...

**Comment by laurentpetit** [comment] 2015-08-13 14:30
Should I launch the virtual device emulator via `tools\android avd` before launching `lein droid doall` ?

**Comment by arichiardi** [comment] 2015-08-13 14:31
I think your error happens before, ```dexing``` is basically the step that converts classes (and resources) to the Android java format.

**Comment by laurentpetit** [comment] 2015-08-13 14:31
@arichiardi right now I'm all leiningen 2.5.1 from the command line, though, and it has been reported to work, what's happening then... ?

**Comment by arichiardi** [comment] 2015-08-13 14:32
Tried ```lein new droid robo-test com.robo.test :target-sdk 19 :min-sdk 15```, result:
```
...
Retrieving org/clojure/core.incubator/0.1.2/core.incubator-0.1.2.jar from central
Retrieving de/ubercode/clostache/clostache/1.4.0/clostache-1.4.0.jar from clojars
Using lein-droid 0.4.0-alpha6
Creating project robo-test ...
```

**Comment by laurentpetit** [comment] 2015-08-13 14:33
ok, what's kind of weird is that the multidex not found issue happens with lein for me, and not during project creation, but when doing lein droid doall. So same error, but not same step, and not same tool

**Comment by arichiardi** [comment] 2015-08-13 14:34
Because ```doall``` is basically compiling, dexing and deploying, that is why it happens there...I am trying the same here as we speak.

**Comment by arichiardi** [comment] 2015-08-13 14:35
Same error here:
```
lein droid doall
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.pom from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0-beta3-r2/clojure-1.7.0-beta3-r2.pom from clojars
Retrieving org/clojure-android/clojure/1.7.0/clojure-1.7.0.jar from clojars
Retrieving neko/neko/4.0.0-alpha2/neko-4.0.0-alpha2.jar from clojars
Could not find artifact com.android.support:multidex:aar:1.0.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in clojars (https://clojars.org/repo/)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-support (file://extras/android/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in android-play-services (file://extras/google/m2repository)
Could not find artifact com.android.support:multidex:aar:1.0.0 in maven-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

Time to file a issue there on ```lein-droid```?

**Comment by laurentpetit** [comment] 2015-08-13 14:36
I do not have a `m2repository` folder in my `extras` folder:
```
android % pwd
/Users/laurentpetit/android-sdk-macosx/extras/android
android % ls
support
```

**Comment by laurentpetit** [comment] 2015-08-13 14:36
Yes, sure. Same error on different platforms.

**Comment by roti** [comment] 2015-08-13 14:37
@laurentpetit After creating a new project with the lein-droid template, you need to change 
```
:android {:sdk-path "/path/to/android-sdk-linux_x86"}
```
in project.clj before running `lein droid doall`. I'm guessing that's why artifact `com.android.support:multidex:aar:1.0.0` is not found.

Also, when adding android libraries in `:dependencies` you need to include the extension, like this:
```
:dependencies [[com.google.android.gms/play-services-maps "7.5.0" :extension "aar"]]
```

**Comment by laurentpetit** [comment] 2015-08-13 14:37
Will do

**Comment by arichiardi** [comment] 2015-08-13 14:38
Yes, sorry I forgot a step, you should download it (I think is called M2 repository or the like) through the SDK manager (either with Eclipse's or Android Studio's package manager).
I now want to try to give ```lein-droid``` the explicit path to ```multidex``` using ```:external-classes-paths``` option.

**Comment by arichiardi** [comment] 2015-08-13 14:42
Mmm...checking the [doc](https://github.com/clojure-android/lein-droid/wiki/Tutorial#support-libraries) here it says that the ```.m2repository``` folder should be included by default...

**Comment by laurentpetit** [comment] 2015-08-13 14:45
I double checked, there's none

**Comment by laurentpetit** [comment] 2015-08-13 14:48
I don't have Android Support Repository checked and installed. Maybe this is it

**Comment by arichiardi** [comment] 2015-08-13 14:48
[This](https://sites.google.com/a/android.com/tools/recent/updatingsdkfromcommand-line) is how you update from command line (with no Eclipse plugin).
I think [thes](https://stackoverflow.com/questions/12382555/android-support-library-manual-download) downloads the repository folder.

**Comment by laurentpetit** [comment] 2015-08-13 14:52
OK that was it, not installing "Android Support Library"

**Comment by arichiardi** [comment] 2015-08-13 14:54
Weird, I had ```multidex``` ```1.0.1``` in my installation, and it was giving me the error. It might need exactly the ```1.0.0``` or maybe I need to specify the ```build-tools``` version...in any case good that you solved!

**Comment by laurentpetit** [comment] 2015-08-13 14:55
Yeah, ok, so now I managed to get `lein droid doall` to succeed via the command line.
As an extra bonus for doing all this: I'd like to see the app work in the emulator, just for the fun. How do I do that?

**Comment by arichiardi** [comment] 2015-08-13 14:57
If you have the Eclipse plugin you have to create an instance of the emulator in the AVD manager...
Then start it, and afterwards ```lein droid doall``` should deploy. Moreover ```lein droid install``` does that as well (but does not compile)

**Comment by laurentpetit** [comment] 2015-08-13 14:59
I'd like to go totally without eclipse right now, to better understand the moving parts.
I have done this, but it complains:
```
myapp % lein-stable droid run
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Launching APK...
No devices are attached.
```

**Comment by arichiardi** [comment] 2015-08-13 15:00
maybe the best then would be to attach an Android device through USB.
Or try to follow [this](https://stackoverflow.com/questions/4974568/how-do-i-launch-the-android-emulator-from-the-command-line)

**Comment by laurentpetit** [comment] 2015-08-13 15:01
OK, I started `tools/android avd`, and try to create a new Android Virtual Device.
I'm overwhelmed by the number of options to choose from

**Comment by arichiardi** [comment] 2015-08-13 15:03
Leave everything as default, mdpi for density, no sd card emulation, no keyboard...yeah it is messy a bit...that why I usually use Genymotion. But I guess for such a short test it is not worth installing it.

**Comment by laurentpetit** [comment] 2015-08-13 15:04
ok. So I assume the `lein droid ..` options do not take care of launching the emulator. Launching one right now...

**Comment by roti** [comment] 2015-08-13 15:05
Just take a Device Definition, create a new device from it (Device Definitions are templates). Important thing is that you set CPU to Intel, otherwise the emulator will run slow.

On windows you also need to install HAXM, on Mac probably not. 

lein droid deploys automatically on the device if you have the emulator running. (it also works if you have a real device attached to USB, and have USB debugging enabled on the device).

**Comment by laurentpetit** [comment] 2015-08-13 15:06
Ahh, I got the other way around. I will start from a Device Definition (which one do you suggest?).
It did already complain about HAXM. Is that something I need to install separately?

**Comment by laurentpetit** [comment] 2015-08-13 15:10
so there's no such thing as HAXM for OS X or Linux, it only exists as a Windows feature. Will have to find out how to disable it.

**Comment by roti** [comment] 2015-08-13 15:10
HAXM is something you need to install separately (only on windows as far as I know). 
You need to download it first with the SDK Manager, like everything else, and then run the installer from `\extras\intel\Hardware_Accelerated_Execution_Manager`.

HAXM is only used to boost performance of the emulator, when CPU is set to Intel. If you don't have it, emulator will work, but reeeeeeeealy slow.

**Comment by laurentpetit** [comment] 2015-08-13 15:12
Got it. Thanks.

**Comment by laurentpetit** [comment] 2015-08-13 15:18
Almost there. lein-droid does not complain, the emulator is started, but I cannot see the app

**Comment by laurentpetit** [comment] 2015-08-13 15:19
oh wait, it works!

**Comment by arichiardi** [comment] 2015-08-13 15:19
not even in the menu? ```lein droid install``` should install it, then in then you can see it

**Comment by laurentpetit** [comment] 2015-08-13 15:19
Great ! I had to redo `lein droid doall`when the emulator was up.

**Comment by arichiardi** [comment] 2015-08-13 15:20
:+1: !

**Comment by laurentpetit** [comment] 2015-08-13 15:21
ok, now same thing with lein commands from ccw

**Comment by laurentpetit** [comment] 2015-08-13 15:32
OK, so all of the errors are present because CCW was not able to create the Leiningen Dependencies Classpath. Will look into that. But later, need to go now. CU.

**Comment by laurentpetit** [comment] 2015-08-13 15:36
So I can reproduce that "Reset Project Configuration" does not work as expected. I don't have the dex not found error anymore in the console, but still, nothing happens.

Looks like a very good candidate issue for liberating CCW from embedding leiningen-core.

**Comment by arichiardi** [comment] 2015-08-13 15:46
I second that! Go go go! :smile:

**Comment by laurentpetit** [comment] 2015-08-13 16:00
The expected downside is that when doing a change to project.clj it will
take longer than today to have the deps updated since a Lein jvm process
will be called.
But the upside will be that far less tricks will be involved to make it
work, and it will be more future proof, benefiting from the real leiningen
power and corner cases :)

Le jeudi 13 août 2015, Andrea Richiardi <notifications@github.com> a écrit :

> I second that! Go go go! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/issues/840#issuecomment-130734546>.
>


-- 
Laurent Petit

**Comment by laurentpetit** [comment] 2015-08-15 00:15
So the first problem is also present with leiningen, if you try e.g. to call `lein classpath`.
See https://github.com/clojure-android/lein-droid/issues/131 for detail.

It seems like lein-droid does not, or cannot add the `m2repositories`to the list of repositories, in time for leiningen to be able to do its work.

Dunno what I'll be able to do if even leiningen itself does not detect the classpath or the list of deps when asked to do so.

**Comment by laurentpetit** [comment] 2015-08-20 17:00
Hi @roti can you go to lein-droid issue https://github.com/clojure-android/lein-droid/issues/131 and mark your interest for its fix in the comments?

I'll now work on the `lein droid doall` which hangs on CCW

**Comment by laurentpetit** [comment] 2015-08-20 18:36
OK, so concerning `lein droid doall` called from `Alt + L L`, I can reproduce the issue quite easily. And it's a problem with the way CCW 'enhances' leiningen before calling it. Still digging ...

**Comment by laurentpetit** [comment] 2015-08-20 18:54
Found the issue for `lein droid doall` !!! I'm happy :-) (CCW injected a future for leiningen subtasks, but no no, futures don't use daemon threads, so they prevent JVMs to shutdown if the subprocess task does not explicitly call shutdown-agents => fixed)

**Closed** 2015-08-20 19:19 UTC
Labels: Priority-High

**Comment by arichiardi** [comment] 2015-08-20 19:30
Ooooh wow, good job! A lot of problem with this missed shutdown-agents right? I should keep it in the back of my mind...

**Comment by laurentpetit** [comment] 2015-08-21 11:53
lein-droid 0.4.0 has been published by its author and it partially solves the classpath problem. Partially because now, CCW gets a classpath from lein, that's an improvement, but the classpath is still incomplete.
